FROM php:7.0-cli

ARG BUILD_DATE
ARG VCS_REF

LABEL org.label-schema.build-date=$BUILD_DATE \
      org.label-schema.vcs-url="https://github.com/iWader/laravel-ci.git" \
      org.label-schema.vcs-ref=$VCS_REF \
      org.label-schema.schema-version="1.0" \
      org.label-schema.vendor="iwader.co.uk" \
      org.label-schema.name="laravel-ci" \
      org.label-schema.description="Docker for Laravel in a CI environment" \
      org.label-schema.url="https://github.com/iwader/laravel-ci"

ENV NVM_VERSION v0.33.2

RUN apt-get update

# Required to add yarn package repository
RUN apt-get install -y apt-transport-https

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list

RUN apt-get update && apt-get install -y \
        libmcrypt-dev \
        git \
        unzip \
        wget \
        libpng-dev \
        libsqlite3-dev \
        libgconf-2-4 \
        libfontconfig1 \
        chromium \
        xvfb \
        yarn

RUN docker-php-ext-install -j$(nproc) mcrypt pdo_mysql pdo_sqlite gd zip

RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/${NVM_VERSION}/install.sh | bash

COPY ./scripts ./scripts

RUN ./scripts/composer.sh
