#!/bin/bash

echo "Build hook running"

if [ "$SOURCE_BRANCH" == "master" ]; then

    # Standard build

    TAG=$(echo $IMAGE_NAME | cut -d':' -f 2)

    docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                 --build-arg VCS_REF=`git rev-parse --short HEAD` \
                 -t $IMAGE_NAME -f Dockerfile-$TAG .

else

    # Test build

    docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
                 --build-arg VCS_REF=`git rev-parse --short HEAD` \
                 -t $IMAGE_NAME -f Dockerfile-$CACHE_TAG .

fi