#!/bin/bash

TAG=$(echo $IMAGE_NAME | cut -d':' -f 2)

if [ "$TAG" == "7.2" ]; then
    for NEW_TAG in {7,latest}; do
        docker tag $IMAGE_NAME $DOCKER_REPO:$NEW_TAG
        docker push $DOCKER_REPO:$NEW_TAG
    done
fi